// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using PrepaidWallet.Data;

#nullable disable

namespace PrepaidWallet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrepaidWallet.Models.BalanceTransaction", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<decimal>("Amount").HasColumnType("decimal(18,2)");
                b.Property<decimal>("BalanceAfter").HasColumnType("decimal(18,2)");
                b.Property<decimal>("BalanceBefore").HasColumnType("decimal(18,2)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");
                b.Property<string>("OperatorName").IsRequired().HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");
                b.Property<int>("PrepaidUserId").HasColumnType("int");
                b.Property<string>("Remark").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<int>("TransactionType").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("PrepaidUserId");
                b.ToTable("BalanceTransactions");
            });

            modelBuilder.Entity("PrepaidWallet.Models.PrepaidUser", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<decimal>("Balance").HasColumnType("decimal(18,2)").HasDefaultValue(0.00m);
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");
                b.Property<string>("Email").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<bool>("IsActive").HasColumnType("bit").HasDefaultValue(true);
                b.Property<string>("PhoneNumber").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.HasKey("Id");
                b.HasIndex("Email").IsUnique()
                    .HasFilter("[Email] IS NOT NULL AND [Email] <> ''");
                b.HasIndex("PhoneNumber").IsUnique();
                b.ToTable("PrepaidUsers");
            });

            modelBuilder.Entity("PrepaidWallet.Models.BalanceTransaction", b =>
            {
                b.HasOne("PrepaidWallet.Models.PrepaidUser", "PrepaidUser")
                    .WithMany()
                    .HasForeignKey("PrepaidUserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("PrepaidUser");
            });
#pragma warning restore 612, 618
        }
    }
}
